export const GET_RECIPES = 'GET_RECIPES';
export const GET_RECIPE_DETAIL = 'GET_RECIPE_DETAIL';
export const GET_DIETS = 'GET_DIETS';
export const GET_YOUR_RECIPES = 'GET_YOUR_RECIPES';
export const GET_FILTERED_RECIPES = 'GET_FILTERED_RECIPES';
export const CREATED_RECIPE = 'CREATED_RECIPE';
export const FILTERS_OFF = 'FILTERS_OFF';
